apiVersion: v1
kind: Pod
metadata:
  name: registry
  namespace: registry
spec:
  containers:
    - name: registry
      image: registry
      volumeMounts:
      - mountPath: "/data-internal"
        name: registry-data
  volumes:
    - name: registry-data
      hostPath:
        path: /data/registry
        type: Directory