apiVersion: v1
kind: Pod
metadata:
  name: registry
  namespace: registry
  labels:
    app.kubernetes.io/name: registry
spec:
  containers:
    - name: registry
      image: registry
      volumeMounts:
        - mountPath: "/data-internal"
          name: registry-data
      ports:
        - containerPort: 5000
  volumes:
    - name: registry-data
      hostPath:
        path: /data/registry
        type: Directory