apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
  namespace: registry
  labels:
    type: local
spec:
  storageClassName: hostpath
  claimRef:
    name: registry
    namespace: registry
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/registry
  persistentVolumeReclaimPolicy: Retain