apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: Dummy Inc.
  secretName: ca-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
