adminPassword: Harbor12345

exposureType: ingress

ingress:
  core:
    hostname: harbor.sandbox.local
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    
    extraTls:
      - secretName: harbor-core-crt
        hosts:
          - harbor.sandbox.local
       
persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-registry

registry:
  credentials:
    username: lambda
    password: lambda

  podSecurityContext:
    supplementalGroups:
      - 0