expose:
  type: ingress

  tls:
    certSource: secret

    secret:
      secretName: harbor-crt

  ingress:
    hosts:
      core: harbor.sandbox.local

    annotations:
      cert-manager.io/cluster-issuer: ca-issuer

registry:
  credentials:
    username: lambda
    password: lambda

externalURL: https://harbor.sandbox.local