apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry
spec:
  storageClassName: standard
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/registry
  persistentVolumeReclaimPolicy: Retain