apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app.kubernetes.io: harbor-registry
  resources:
    requests:
      storage: 5Gi