apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: harbor-registry
  resources:
    requests:
      storage: 5Gi